global using System.Text.Json;
global using System.Collections.ObjectModel;
global using System.Collections.Specialized;
global using GeoJSON.Text;
global using GeoJSON.Text.Feature;
global using GeoJSON.Text.Geometry;
global using MapboxMaui;
global using MapboxMaui.Expressions;
global using MapboxMaui.Styles;
global using MapboxMaui.Offline;
global using MapboxMaui.Annotations;
global using iOSPage = Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific.Page;
global using ScreenPosition = Microsoft.Maui.Graphics.Point;
global using MapPosition = GeoJSON.Text.Geometry.Position;